### PR TITLE
readme(shell): add .zsh configuration for WSL

### PR DESCRIPTION
**Pull request by kaniaorzel**
HI, I started with WSL 2, and I feel a lack of .zsh. I thinking about writing how to configure .zsh, but after that, I found an article from this PR :)

### CODE REVIEW

**Comment by sirredbeard** [comment]
It seems every specific to .zsh in another more general terminal area. It also requires cmdr so that adds complexity for a new user. Maybe in the WSL tools section?

**Comment by kaniaorzel** [comment]
@sirredbeard thanks for the comment. I moved the link to another section. 

btw. I am thinking about putting to this repository https://prettier.io/ and `.prettierrc`. This tool could help contributors to collaborate and not thinking about markdown format :) WDYT?

**Comment by sirredbeard** [comment]
Reading up on this. This is just a file added to the repo?

**Comment by kaniaorzel** [comment]
@sirredbeard this is config file, and we need to describe in info for contributors how to install it in system

**Comment by sirredbeard** [comment]
Is it a linter where we would specify GitHub markdown? There is an official awesome list linter that we should be using.

**Comment by kaniaorzel** [comment]
Oh I see. I found awesome-linter. And you are using remark-parse, and prettier using the same. But without exceptions (https://prettier.io/docs/en/options.html).

**Comment by kaniaorzel** [comment]
@sirredbeard if you want I could prepare config for prettier covering all exceptions, that could be easier to maintain :)

**Comment by HanabishiRecca** [comment]
`grml-zsh` is better and solves all the problems (IMHO).

**Pull request closed without merging**
