### PR TITLE
Remove ManjaroWSL from list of unofficial distros

### PR DESCRIPTION
**Pull request by sileshn**
*Manjaro team has issues with using the word "Manjaro" in the title

### CODE REVIEW

**Comment by sirredbeard** [comment]
Merged. Did you get a cease and desist letter from them or something along those lines?

**Comment by sileshn** [comment]
They asked me to remove the word "Manjaro" from the title. Didn't know how to name a project for Manjaro without using the word manjaro.

**Comment by zzbe** [comment]
Name it Wenzi, after Mawenzi mountain. :p

**Comment by sirredbeard** [comment]
So is it gone now?

**Comment by sileshn** [comment]
Yup

**Comment by GalGreenfield** [comment]
> Yup

Would you be consider bringing it back under a different name? I'm having issues with the system and want to make sure I reinstall from the latest files you released.

**Comment by GalGreenfield** [comment]
> Yup

Would you be willing to bring it back under a different name? I have an old install of it that I want to reinstall and want to make sure I do it with the latest release.

**Comment by sileshn** [comment]
Na, too much of a hassle. There are a few idiots on the Manjaro forum who don't even know what wsl is and think installing ManjaroWSL will give them the same experience of running Manjaro as a linux distro. They then create posts on the forum complaining about their experience. That's how all this started in the first place. 

You usually won't need a newer release for a reinstall unless I have added new features. Just contact me on my email (_available on my github profile_) if you need a updated version in future. You can download the updated release from [here](https://onedrive.live.com/download?cid=A4DEE18D4370FE4F&resid=A4DEE18D4370FE4F%216010&authkey=AGqEzUdVd0elxJE). If you need systemd support, execute the commands as root and restart the distro.

`wget https://raw.githubusercontent.com/diddledani/one-script-wsl2-systemd/main/src/sudoers -O /etc/sudoers.d/wsl2-systemd`
`wget https://raw.githubusercontent.com/diddledani/one-script-wsl2-systemd/main/src/00-wsl2-systemd.sh -P /etc/profile.d/`
`sed -i 's/%sudo/%wheel/g' /etc/sudoers.d/wsl2-systemd`
`sed -i '/\\nSystemd/d' /etc/profile.d/00-wsl2-systemd.sh`

**Comment by mrex** [comment]
I've been wondering what happened to ManjaroWSL for a while now. Reading that forum thread makes me shake my head. It really makes me sad to see how a bunch of people with no clue what they are talking about has lead to this.

I tried ManjaroWSL a while ago, after I couldn't figure out how to get DBUS to work properly in ArchWSL. It worked out of the box in ManjaroWSL. Now this option is gone for others that might have the same issues.

**Comment by sileshn** [comment]
> 

You can try if dbus works in [these](https://github.com/sileshn/ArchWSL2/releases) ArchWSL2 builds.

**Comment by mrex** [comment]
Thank you, I will give it a try.

**Comment by mrex** [comment]
> You can try if dbus works in [these](https://github.com/sileshn/ArchWSL2/releases) ArchWSL2 builds.

It does work! Apart from that, I finally looked into getting systemd to work with the script you linked to, which is working great, too. That should make working with services a lot smoother. Thank you for your work on all these distributions for WSL! I'm going to retire the Manjaro distribution and move on to pure Arch now.

**Comment by codesardine** [comment]
> They mailed me asking to remove the word "Manjaro" from the title. Didn't know how to name a project for Manjaro without using the word manjaro.

Hi there, I am from the manjaro team, I was following your project until i realize it was gone, ho contacted you asking to remove the name? @sileshn

**Comment by sileshn** [comment]
I don't remember. Could be this guy, Frede Hundewadt

**Comment by sileshn** [comment]
Manjaro for WSL is back up again if anyone is interested. Received permission from the Manjaro core team.

https://github.com/sileshn/ManjaroWSL2

**Comment by orange-pig** [comment]
> Manjaro for WSL is back up again if anyone is interested. Received permission from the Manjaro core team.
> 
> https://github.com/sileshn/ManjaroWSL2

Congratulations ManjaroWSL comeback, the ArchWSL works well for me :P.

**Pull request merged**
